name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Baixar o código
        uses: actions/checkout@v4
        
      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          
      - name: Instalar Dependências e Compilar
        # 👇 A MÁGICA: Avisamos o robô para entrar na sua subpasta!
        working-directory: ./loja-app
        run: |
          npm install
          npm run build
          
      - name: Preparar o GitHub Pages
        uses: actions/configure-pages@v4
        
      - name: Fazer o Upload da pasta 'dist'
        uses: actions/upload-pages-artifact@v3
        with:
          # 👇 A MÁGICA 2: Mostramos onde a pasta 'dist' foi criada
          path: './loja-app/dist' 
          
      - name: Publicar o Site
        id: deployment
        uses: actions/deploy-pages@v4